package content

func TutorialSource() ContentSource {
	return ContentSource{
		StartRoomID: "room.tutorial.hall",
		Verbs: []VerbSource{
			{ID: "light", MessageKey: "verb.light.default"},
		},
		Rooms: []RoomSource{
			{ID: "room.tutorial.hall", NameKey: "room.tutorial.hall.name", DescriptionKey: "room.tutorial.hall.description"},
			{ID: "room.tutorial.item_yard", NameKey: "room.tutorial.item_yard.name", DescriptionKey: "room.tutorial.item_yard.description"},
			{ID: "room.tutorial.lock_hall", NameKey: "room.tutorial.lock_hall.name", DescriptionKey: "room.tutorial.lock_hall.description"},
			{ID: "room.tutorial.lock_chamber", NameKey: "room.tutorial.lock_chamber.name", DescriptionKey: "room.tutorial.lock_chamber.description"},
			{ID: "room.tutorial.quest_start", NameKey: "room.tutorial.quest_start.name", DescriptionKey: "room.tutorial.quest_start.description"},
			{ID: "room.tutorial.weight_room", NameKey: "room.tutorial.weight_room.name", DescriptionKey: "room.tutorial.weight_room.description"},
			{ID: "room.tutorial.dark_cave", NameKey: "room.tutorial.dark_cave.name", DescriptionKey: "room.tutorial.dark_cave.description", Dark: true},
		},
		Items: []ItemSource{
			// === 大厅出口 ===
			{
				ID: "item.hall.north", DisplayNameKey: "item.hall.north.name", InnerNameKey: "item.hall.north.inner_name",
				DescriptionKey: "item.hall.north.description", InitialRoom: "room.tutorial.hall",
				Tags: []SourceTag{{ID: TagExit, Params: map[string]string{"target_room_id": "room.tutorial.item_yard"}}},
			},
			{
				ID: "item.hall.east", DisplayNameKey: "item.hall.east.name", InnerNameKey: "item.hall.east.inner_name",
				DescriptionKey: "item.hall.east.description", InitialRoom: "room.tutorial.hall",
				Tags: []SourceTag{{ID: TagExit, Params: map[string]string{"target_room_id": "room.tutorial.lock_hall"}}},
			},
			{
				ID: "item.hall.portal", DisplayNameKey: "item.hall.portal.name", InnerNameKey: "item.hall.portal.inner_name",
				DescriptionKey: "item.hall.portal.description", InitialRoom: "room.tutorial.hall",
				Tags: []SourceTag{{ID: TagExit, Params: map[string]string{"target_room_id": "room.tutorial.quest_start", "direction": "portal"}}},
			},
			// === 物品庭院出口 ===
			{
				ID: "item.yard.south", DisplayNameKey: "item.yard.south.name", InnerNameKey: "item.yard.south.inner_name",
				DescriptionKey: "item.yard.south.description", InitialRoom: "room.tutorial.item_yard",
				Tags: []SourceTag{{ID: TagExit, Params: map[string]string{"target_room_id": "room.tutorial.hall"}}},
			},
			// === 物品庭院容器 ===
			{
				ID: "item.yard.chest", DisplayNameKey: "item.yard.chest.name", InnerNameKey: "item.yard.chest.inner_name",
				DescriptionKey: "item.yard.chest.description", InitialRoom: "room.tutorial.item_yard",
				Tags: []SourceTag{{ID: TagContainer, Params: map[string]string{"capacity": "5"}}},
			},
			// === 锁钥厅出口 ===
			{
				ID: "item.lock_hall.west", DisplayNameKey: "item.lock_hall.west.name", InnerNameKey: "item.lock_hall.west.inner_name",
				DescriptionKey: "item.lock_hall.west.description", InitialRoom: "room.tutorial.lock_hall",
				Tags: []SourceTag{{ID: TagExit, Params: map[string]string{"target_room_id": "room.tutorial.hall"}}},
			},
			{
				ID: "item.lock_hall.east", DisplayNameKey: "item.lock_hall.east.name", InnerNameKey: "item.lock_hall.east.inner_name",
				DescriptionKey: "item.lock_hall.east.description", InitialRoom: "room.tutorial.lock_hall",
				Tags: []SourceTag{
					{ID: TagExit, Params: map[string]string{"target_room_id": "room.tutorial.lock_chamber"}},
					{ID: TagLockable, Params: map[string]string{"key_item_id": "item.tutorial.old_lantern"}},
				},
			},
			// === 密室出口 ===
			{
				ID: "item.lock_chamber.west", DisplayNameKey: "item.lock_chamber.west.name", InnerNameKey: "item.lock_chamber.west.inner_name",
				DescriptionKey: "item.lock_chamber.west.description", InitialRoom: "room.tutorial.lock_chamber",
				Tags: []SourceTag{{ID: TagExit, Params: map[string]string{"target_room_id": "room.tutorial.lock_hall"}}},
			},
			// === 任务起点出口 ===
			{
				ID: "item.quest_start.portal", DisplayNameKey: "item.quest_start.portal.name", InnerNameKey: "item.quest_start.portal.inner_name",
				DescriptionKey: "item.quest_start.portal.description", InitialRoom: "room.tutorial.quest_start",
				Tags: []SourceTag{{ID: TagExit, Params: map[string]string{"target_room_id": "room.tutorial.hall", "direction": "portal"}}},
			},
			// === 游戏物品 ===
			{
				ID:             "item.tutorial.old_lantern",
				DisplayNameKey: "item.tutorial.old_lantern.name",
				InnerNameKey:   "item.tutorial.old_lantern.inner_name",
				DescriptionKey: "item.tutorial.old_lantern.description",
				Aliases: []TextKey{
					"item.tutorial.old_lantern.alias.jiuyoudeng",
					"item.tutorial.old_lantern.alias.old_lantern",
				},
				InitialRoom: "room.tutorial.lock_hall",
				Tags:        []SourceTag{{ID: TagCarryable}, {ID: TagLightable}},
				Weight:      5,
				Volume:      2,
			},
			{
				ID:             "item.tutorial.practice_sword",
				DisplayNameKey: "item.tutorial.practice_sword.name",
				InnerNameKey:   "item.tutorial.practice_sword.inner_name",
				DescriptionKey: "item.tutorial.practice_sword.description",
				Aliases:        []TextKey{"item.tutorial.practice_sword.alias.lianximujian"},
				InitialRoom:    "room.tutorial.item_yard",
				Tags:           []SourceTag{{ID: TagCarryable}},
				Weight:         3,
				Volume:         3,
			},
			{
				ID:             "item.tutorial.training_relic",
				DisplayNameKey: "item.tutorial.training_relic.name",
				InnerNameKey:   "item.tutorial.training_relic.inner_name",
				DescriptionKey: "item.tutorial.training_relic.description",
				Aliases: []TextKey{
					"item.tutorial.training_relic.alias.liangonghuizhang",
					"item.tutorial.training_relic.alias.training_relic",
				},
				InitialRoom: "room.tutorial.lock_chamber",
				Tags:        []SourceTag{{ID: TagCarryable}},
				Weight:      1,
				Volume:      1,
			},
			// === 测重房出口 ===
			{
				ID: "item.yard.east", DisplayNameKey: "item.yard.east.name",
				InnerNameKey: "item.yard.east.inner_name", DescriptionKey: "item.yard.east.description",
				InitialRoom: "room.tutorial.item_yard",
				Tags:        []SourceTag{{ID: TagExit, Params: map[string]string{"target_room_id": "room.tutorial.weight_room"}}},
			},
			{
				ID: "item.weight_room.west", DisplayNameKey: "item.weight_room.west.name",
				InnerNameKey: "item.weight_room.west.inner_name", DescriptionKey: "item.weight_room.west.description",
				InitialRoom: "room.tutorial.weight_room",
				Tags:        []SourceTag{{ID: TagExit, Params: map[string]string{"target_room_id": "room.tutorial.item_yard"}}},
			},
			{
				ID: "item.weight_room.north", DisplayNameKey: "item.weight_room.north.name",
				InnerNameKey: "item.weight_room.north.inner_name", DescriptionKey: "item.weight_room.north.description",
				InitialRoom: "room.tutorial.weight_room",
				Tags:        []SourceTag{{ID: TagExit, Params: map[string]string{"target_room_id": "room.tutorial.dark_cave"}}},
			},
			{
				ID: "item.dark_cave.south", DisplayNameKey: "item.dark_cave.south.name",
				InnerNameKey: "item.dark_cave.south.inner_name", DescriptionKey: "item.dark_cave.south.description",
				InitialRoom: "room.tutorial.dark_cave",
				Tags:        []SourceTag{{ID: TagExit, Params: map[string]string{"target_room_id": "room.tutorial.weight_room"}}},
			},
			// === 测重房物品 ===
			{
				ID: "item.tutorial.small_weight", DisplayNameKey: "item.tutorial.small_weight.name",
				InnerNameKey: "item.tutorial.small_weight.inner_name", DescriptionKey: "item.tutorial.small_weight.description",
				InitialRoom: "room.tutorial.weight_room",
				Tags:        []SourceTag{{ID: TagCarryable}},
				Weight:      1, Volume: 1,
			},
			{
				ID: "item.tutorial.medium_weight", DisplayNameKey: "item.tutorial.medium_weight.name",
				InnerNameKey: "item.tutorial.medium_weight.inner_name", DescriptionKey: "item.tutorial.medium_weight.description",
				InitialRoom: "room.tutorial.weight_room",
				Tags:        []SourceTag{{ID: TagCarryable}},
				Weight:      5, Volume: 2,
			},
			{
				ID: "item.tutorial.large_weight", DisplayNameKey: "item.tutorial.large_weight.name",
				InnerNameKey: "item.tutorial.large_weight.inner_name", DescriptionKey: "item.tutorial.large_weight.description",
				InitialRoom: "room.tutorial.weight_room",
				Tags:        []SourceTag{{ID: TagCarryable}},
				Weight:      10, Volume: 5,
			},
			{
				ID: "item.tutorial.iron_ingot", DisplayNameKey: "item.tutorial.iron_ingot.name",
				InnerNameKey: "item.tutorial.iron_ingot.inner_name", DescriptionKey: "item.tutorial.iron_ingot.description",
				InitialRoom: "room.tutorial.weight_room",
				Aliases:     []TextKey{"item.tutorial.iron_ingot.alias.tieding"},
				Tags:        []SourceTag{{ID: TagCarryable}},
				Weight:      8, Volume: 1,
			},
			{
				ID: "item.tutorial.cotton_bale", DisplayNameKey: "item.tutorial.cotton_bale.name",
				InnerNameKey: "item.tutorial.cotton_bale.inner_name", DescriptionKey: "item.tutorial.cotton_bale.description",
				InitialRoom: "room.tutorial.weight_room",
				Aliases:     []TextKey{"item.tutorial.cotton_bale.alias.mianhuabao"},
				Tags:        []SourceTag{{ID: TagCarryable}},
				Weight:      1, Volume: 8,
			},
			{
				ID: "item.tutorial.barbell", DisplayNameKey: "item.tutorial.barbell.name",
				InnerNameKey: "item.tutorial.barbell.inner_name", DescriptionKey: "item.tutorial.barbell.description",
				InitialRoom: "room.tutorial.weight_room",
				Aliases:     []TextKey{"item.tutorial.barbell.alias.gangling"},
				Tags:        []SourceTag{{ID: TagCarryable}},
				Weight:      15, Volume: 5,
			},
			{
				ID: "item.tutorial.boulder", DisplayNameKey: "item.tutorial.boulder.name",
				InnerNameKey: "item.tutorial.boulder.inner_name", DescriptionKey: "item.tutorial.boulder.description",
				InitialRoom: "room.tutorial.weight_room",
				Weight:      999, Volume: 999,
			},
			// === 黑暗洞穴物品 ===
			{
				ID: "item.tutorial.treasure_chest", DisplayNameKey: "item.tutorial.treasure_chest.name",
				InnerNameKey: "item.tutorial.treasure_chest.inner_name", DescriptionKey: "item.tutorial.treasure_chest.description",
				InitialRoom: "room.tutorial.dark_cave",
				Tags:        []SourceTag{{ID: TagCarryable}},
				Weight:      2, Volume: 1,
			},
			// === 便携容器 ===
			{
				ID: "item.tutorial.storage_pouch", DisplayNameKey: "item.tutorial.storage_pouch.name",
				InnerNameKey: "item.tutorial.storage_pouch.inner_name", DescriptionKey: "item.tutorial.storage_pouch.description",
				InitialRoom: "room.tutorial.weight_room",
				Tags:        []SourceTag{{ID: TagCarryable}, {ID: TagContainer, Params: map[string]string{"capacity": "5"}}},
				Weight:      2, Volume: 1,
			},
		},
		Quests: []QuestSource{
			{
				ID:      "quest.tutorial.first_steps",
				NameKey: "quest.tutorial.first_steps.name",
				StageIDs: []QuestStageID{
					"quest.tutorial.first_steps.stage.get_lantern",
					"quest.tutorial.first_steps.stage.enter_chamber",
					"quest.tutorial.first_steps.stage.examine_relic",
				},
			},
		},
		QuestStages: []QuestStageSource{
			{
				ID:      "quest.tutorial.first_steps.stage.get_lantern",
				TextKey: "quest.tutorial.first_steps.stage.get_lantern.text",
				FinishConditions: []QuestConditionSource{
					{Kind: QuestConditionGotItem, ItemID: "item.tutorial.old_lantern"},
				},
				NextStageID: "quest.tutorial.first_steps.stage.enter_chamber",
			},
			{
				ID:      "quest.tutorial.first_steps.stage.enter_chamber",
				TextKey: "quest.tutorial.first_steps.stage.enter_chamber.text",
				FinishConditions: []QuestConditionSource{
					{Kind: QuestConditionMovedRoom, RoomID: "room.tutorial.lock_chamber"},
				},
				NextStageID: "quest.tutorial.first_steps.stage.examine_relic",
			},
			{
				ID:      "quest.tutorial.first_steps.stage.examine_relic",
				TextKey: "quest.tutorial.first_steps.stage.examine_relic.text",
				FinishConditions: []QuestConditionSource{
					{Kind: QuestConditionExaminedItem, ItemID: "item.tutorial.training_relic"},
				},
			},
		},
		Text: map[TextKey]string{
			// 房间名称与描述
			"room.tutorial.hall.name":              "教学大厅",
			"room.tutorial.hall.description":       "大厅宽敞明亮，四周墙壁上挂着几幅地图。这里连通着多个区域。",
			"room.tutorial.item_yard.name":         "物品庭院",
			"room.tutorial.item_yard.description":  "庭院里散落着各种练习用品，地上还有几把木剑。",
			"room.tutorial.lock_hall.name":         "锁钥厅",
			"room.tutorial.lock_hall.description":  "墙壁上挂着一盏旧油灯，东侧有一扇厚重的铁门。",
			"room.tutorial.lock_chamber.name":      "密室",
			"room.tutorial.lock_chamber.description": "一间昏暗的小室，空气中有股陈旧的灰尘味。",
			"room.tutorial.quest_start.name":       "任务之门",
			"room.tutorial.quest_start.description": "你感到一股神秘的力量在这里流动。",

			// 出口物品
			"item.hall.north.name":          "北方通路",
			"item.hall.north.inner_name":    "north",
			"item.hall.north.description":   "一条向北延伸的石板路。",
			"item.hall.east.name":           "东方通路",
			"item.hall.east.inner_name":     "east",
			"item.hall.east.description":    "一条向东的走廊。",
			"item.hall.portal.name":         "传送门",
			"item.hall.portal.inner_name":   "portal",
			"item.hall.portal.description":  "一扇泛着蓝光的传送门。",
			"item.yard.south.name":          "南方通路",
			"item.yard.south.inner_name":    "south",
			"item.yard.south.description":   "一条向南的石板路，通向大厅。",
			"item.yard.chest.name":          "木箱",
			"item.yard.chest.inner_name":    "chest",
			"item.yard.chest.description":   "一个结实的木箱，看起来能装不少东西。",
			"item.lock_hall.west.name":      "西方通路",
			"item.lock_hall.west.inner_name": "west",
			"item.lock_hall.west.description": "向西返回大厅的通道。",
			"item.lock_hall.east.name":      "铁门",
			"item.lock_hall.east.inner_name": "east",
			"item.lock_hall.east.description": "一扇厚重的铁门，似乎需要什么才能打开。",
			"item.lock_chamber.west.name":      "西方出口",
			"item.lock_chamber.west.inner_name": "west",
			"item.lock_chamber.west.description": "向西返回锁钥厅。",
			"item.quest_start.portal.name":      "传送门",
			"item.quest_start.portal.inner_name": "portal",
			"item.quest_start.portal.description": "一扇泛着蓝光的传送门。",

			// 游戏物品
			"item.tutorial.old_lantern.name":                  "旧油灯",
			"item.tutorial.old_lantern.inner_name":            "old lantern",
			"item.tutorial.old_lantern.description":           "灯罩上蒙着一层灰，里面还剩一点灯油。",
			"item.tutorial.old_lantern.alias.jiuyoudeng":      "jiuyoudeng",
			"item.tutorial.old_lantern.alias.old_lantern":     "old_lantern",
			"item.tutorial.practice_sword.name":               "练习木剑",
			"item.tutorial.practice_sword.inner_name":         "practice sword",
			"item.tutorial.practice_sword.description":        "一把被许多人握过的木剑，剑柄已经磨得发亮。",
			"item.tutorial.practice_sword.alias.lianximujian": "lianximujian",
			"item.tutorial.training_relic.name":                  "练功徽章",
			"item.tutorial.training_relic.inner_name":            "training relic",
			"item.tutorial.training_relic.description":           "一枚金属徽章，上面刻着\"练功有成\"四个字。",
			"item.tutorial.training_relic.alias.liangonghuizhang": "liangonghuizhang",
			"item.tutorial.training_relic.alias.training_relic":  "training_relic",

			// 任务
			"quest.tutorial.first_steps.name":                       "教程任务",
			"quest.tutorial.first_steps.stage.get_lantern.text":     "拿起旧油灯。",
			"quest.tutorial.first_steps.stage.enter_chamber.text":   "进入密室。",
			"quest.tutorial.first_steps.stage.examine_relic.text":   "查看练功徽章。",

				// 测重房
			"room.tutorial.weight_room.name":                    "测重房",
			"room.tutorial.weight_room.description":             "一间摆满各种砝码和重物的房间，墙上贴着\"负重测试\"的牌子。",
			"room.tutorial.dark_cave.name":                     "黑暗洞穴",
			"room.tutorial.dark_cave.description":               "伸手不见五指的黑暗包围着你，什么也看不见。",
			"item.yard.east.name":                               "东方通道",
			"item.yard.east.inner_name":                         "east",
			"item.yard.east.description":                        "一条向东延伸的通道，通向测重房。",
			"item.weight_room.west.name":                        "西方出口",
			"item.weight_room.west.inner_name":                  "west",
			"item.weight_room.west.description":                 "向西返回物品庭院。",
			"item.tutorial.small_weight.name":                   "小砝码",
			"item.tutorial.small_weight.inner_name":             "small weight",
			"item.tutorial.small_weight.description":            "一个很小的砝码，几乎感觉不到重量。",
			"item.tutorial.medium_weight.name":                  "中砝码",
			"item.tutorial.medium_weight.inner_name":            "medium weight",
			"item.tutorial.medium_weight.description":           "一个中等大小的砝码。",
			"item.tutorial.large_weight.name":                   "大砝码",
			"item.tutorial.large_weight.inner_name":             "large weight",
			"item.tutorial.large_weight.description":            "一个沉重的砝码，拎起来有些费劲。",
			"item.tutorial.iron_ingot.name":                     "铁锭",
			"item.tutorial.iron_ingot.inner_name":               "iron ingot",
			"item.tutorial.iron_ingot.description":              "一块沉甸甸的铁锭，体积不大却很重。",
			"item.tutorial.iron_ingot.alias.tieding":            "tieding",
			"item.tutorial.cotton_bale.name":                    "棉花包",
			"item.tutorial.cotton_bale.inner_name":              "cotton bale",
			"item.tutorial.cotton_bale.description":             "一大包棉花，占地方但很轻。",
			"item.tutorial.cotton_bale.alias.mianhuabao":        "mianhuabao",
			"item.tutorial.barbell.name":                        "杠铃",
			"item.tutorial.barbell.inner_name":                  "barbell",
			"item.tutorial.barbell.description":                 "一副沉重的杠铃，一般人举不动。",
			"item.tutorial.barbell.alias.gangling":              "gangling",
			"item.tutorial.boulder.name":                        "巨石",
			"item.tutorial.boulder.inner_name":                  "boulder",
			"item.tutorial.boulder.description":                 "一块嵌在地面的巨石，纹丝不动。",
			"item.weight_room.north.name":                      "北方洞口",
			"item.weight_room.north.inner_name":                "north",
			"item.weight_room.north.description":               "一个幽深的洞口，里面一片漆黑。",
			"item.dark_cave.south.name":                        "南方出口",
			"item.dark_cave.south.inner_name":                  "south",
			"item.dark_cave.south.description":                 "一丝光亮从南方透进来。",
			"item.tutorial.treasure_chest.name":                "宝藏箱",
			"item.tutorial.treasure_chest.inner_name":          "treasure chest",
			"item.tutorial.treasure_chest.description":         "一个小巧的宝箱，里面装满了宝石。",
			"item.tutorial.storage_pouch.name":                  "收纳袋",
			"item.tutorial.storage_pouch.inner_name":            "storage pouch",
			"item.tutorial.storage_pouch.description":           "一个轻便的收纳袋，可以把东西装进去减少占用的空间。",

		// 系统消息
			"system.empty_input":             "你没有输入任何内容",
			"system.help": "可用命令: look/l, go <direction>, north/n, south/s, east/e, west/w, up/u, down/d, northeast/ne, northwest/nw, southeast/se, southwest/sw, get/take <item>, drop <item>, examine/x/inspect <item>, inventory/i, quest, verb/verbs, help\n方向: north/n/北, south/s/南, east/e, west/w, up/u, down/d, northeast/ne, northwest/nw, southeast/se, southwest/sw",
			"system.internal_error":          "服务器内部错误，请稍后重试。",
			"system.look.observed":           "你重新观察了周围。",
			"system.move.blocked":            "你不能往那个方向走。",
			"system.move.locked":             "门锁着。",
			"system.item.not_here":           "这里没有那个东西。",
			"system.item.taken":              "你拿起了{item}。",
			"system.item.not_carried":        "你没有那个东西。",
			"system.item.dropped":            "你放下了{item}。",
			"system.quest.progress":          "任务更新: {state}",
			"system.unknown_command":         "未知命令: {input}",
			"system.room.missing":            "你迷失在不存在的地方。",
		"system.container.cant_open":     "你打不开{item}。",
		"system.container.now_open":      "你打开了{item}。",
		"system.container.cant_close":    "你关不上{item}。",
		"system.container.now_closed":    "你关上了{item}。",
		"system.container.closed":        "{container}是关着的。",
		"system.container.put_fail":      "{error}",
		"system.container.put_success":   "你把{item}放进了{container}。",
		"system.container.get_fail":      "{error}",
		"system.container.get_success":   "你从{container}里拿出了{item}。",
		"system.item.not_in_container":   "{container}里没有那个东西。",
		"system.item.inventory_full":     "背包已满，你拿不了更多了。",
		"system.move.overweight":         "你背不动了，必须先放下一些东西。",

		"system.room.dark":          "太暗了，你什么也看不见。",
		"system.light.not_lightable": "那个东西不能点亮。",
		"system.light.already_lit":   "已经点亮了。",
		"system.light.not_carried":   "你得先拿着那个东西才能点亮。",

			// 内容动词
			"verb.light.default": "你点亮了{item}。",
		},
	}
}
